services:
  nestjs-api-test-db:
    image: postgres:latest
    container_name: nestjs-api-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1233
      POSTGRES_DB: nestjs_api_test_db
    networks:
      - nestjs-api-network
    ports:
      - "5435:5432"
  nestjs-api-db:
    image: postgres:latest
    container_name: nestjs-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1233
      POSTGRES_DB: nestjs_api_db
    networks:
      - nestjs-api-network
    ports:
      - "5432:5432"
networks:
  nestjs-api-network:
    driver: bridge
